# Generated by Django 4.2 on 2023-05-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
