# Generated by Django 4.2 on 2023-04-22 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('user_image', models.ImageField(null=True, upload_to='media/user_images/')),
                ('user_email', models.EmailField(max_length=254, null=True)),
                ('user_contact', models.CharField(max_length=30)),
                ('birthdate', models.DateTimeField(null=True)),
                ('membership_stat', models.CharField(choices=[('N', 'Normal'), ('P', 'Pending'), ('R', 'Rescuer')], default='N', max_length=1)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
