# Generated by Django 4.2 on 2023-04-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_alter_userprofile_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_email',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_contact',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
