# Generated by Django 4.2 on 2023-05-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adoptionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoptText', models.TextField()),
                ('adopt_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('create_date', models.DateTimeField(null=True)),
                ('animalName', models.CharField(max_length=30)),
                ('adoptee_contact', models.CharField(max_length=30, null=True)),
                ('adoptee_location', models.TextField()),
                ('adoptState', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3)),
            ],
        ),
    ]
