# Generated by Django 4.2 on 2023-05-07 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionpost',
            name='adoptee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopt_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
