# Generated by Django 4.2 on 2023-05-08 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adoption', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adoptionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(null=True)),
                ('report_type', models.CharField(choices=[('F', 'F'), ('S', 'S'), ('N', 'N'), ('H', 'H')], default='F', max_length=1)),
                ('adoption_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_posts', to='adoption.adoptionpost')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
