# Generated by Django 4.2 on 2023-05-11 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rescuepost',
            name='location',
        ),
    ]
